from .dynamic_cls_head import *
from .dynamic_multi_cls_head import *
from .dynamic_ressl_head import *
from .densecl_contrastive_head import *
from .similar_mse_head import *
from .similar_cos_head import *
from .label_smooth_head import *
from .debug_head import *
from .fcn_seg_head import FCNSegHead
